name: action test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: runs-on: self-hosted
    steps:
      - name: Login  
        run: |
          pwd
          ls
          whoami
        shell: bash