name: action test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Login  
        run: |
          cd /www
          ./product.sh ${{ secrets.DOMAIN }} {{ secrets.GIT_REPO }}
        shell: bash